# Generated by Django 5.0.10 on 2024-12-16 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tile',
            name='price',
        ),
    ]
