# Generated by Django 5.0.10 on 2024-12-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_tile_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanitaryitem',
            name='price',
        ),
    ]
