# Generated by Django 5.0.10 on 2024-12-16 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_sanitaryitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=15)),
                ('order_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='sanitaryitem',
            old_name='id',
            new_name='item_id',
        ),
        migrations.CreateModel(
            name='OrderSanitaryDetails',
            fields=[
                ('sanitary_itemid', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('article_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanitary_details', to='main.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTileDetails',
            fields=[
                ('tiledetail_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('article_number', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('tile_size', models.CharField(max_length=100)),
                ('box_size', models.CharField(max_length=255)),
                ('peiece_per_box', models.CharField(max_length=255)),
                ('sale_unit', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tile_details', to='main.order')),
            ],
        ),
    ]
