# Generated by Django 5.0.10 on 2024-12-16 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_order_total_bill_amount_order_sanitary_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Total_bill_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sanitary_total',
        ),
    ]
