# Generated by Django 5.0.10 on 2024-12-17 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_ordersanitarydetails_sanitary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersanitarydetails',
            name='sanitary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sanitaryitem'),
        ),
    ]
