# Generated by Django 5.0.10 on 2024-12-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_ordersanitarydetails_sanitary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersanitarydetails',
            name='sanitary',
        ),
        migrations.AddField(
            model_name='order',
            name='sanitary_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
