# Generated by Django 5.0.10 on 2024-12-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_ordersanitarydetails_sanitary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sanitary_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='tiles_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
