# Generated by Django 5.0.10 on 2025-01-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_order_sales_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
