# Generated by Django 4.2.17 on 2024-12-26 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_order_sales_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sales_person',
        ),
    ]
