# Generated by Django 5.0.10 on 2025-01-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_order_sales_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill_number',
            field=models.IntegerField(null=True),
        ),
    ]
