# Generated by Django 5.0.10 on 2025-01-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_ordersanitarydetails_quantity_and_more'),
        ('main', '0017_alter_order_bill_number'),
    ]

    operations = [
    ]
