# Generated by Django 5.0.10 on 2025-01-08 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_merge_20250109_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundOrder',
            fields=[
                ('Refund_order_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=15)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('tiles_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sanitary_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='bill_number',
        ),
        migrations.CreateModel(
            name='RefundOrderSanitaryDetails',
            fields=[
                ('sanitary_itemid', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('article_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Refundorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refundsanitary_details', to='main.refundorder')),
            ],
        ),
        migrations.CreateModel(
            name='RefundOrderTileDetails',
            fields=[
                ('tiledetail_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('article_number', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('tile_size', models.CharField(max_length=100)),
                ('box_size', models.CharField(max_length=255)),
                ('peiece_per_box', models.CharField(max_length=255)),
                ('sale_unit', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Refundorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refundtile_details', to='main.refundorder')),
            ],
        ),
    ]
