# Generated by Django 5.0.10 on 2025-01-08 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_refundorder_remove_order_bill_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refundorder',
            old_name='Refund_order_id',
            new_name='refund_order_id',
        ),
    ]
