# Generated by Django 5.0.10 on 2025-01-08 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_refund_order_id_refundorder_refund_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundordertiledetails',
            name='Refundorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tilerefund_details', to='main.refundorder'),
        ),
    ]
