# Generated by Django 5.0.10 on 2025-01-08 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_refundordertiledetails_refundorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundordersanitarydetails',
            name='Refundorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanitaryrefund_details', to='main.refundorder'),
        ),
    ]
