# Generated by Django 5.0.10 on 2025-01-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_refundordersanitarydetails_refundorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='refundorder',
            name='bill_number',
            field=models.IntegerField(null=True),
        ),
    ]
